"""Database package for BBN Annotation Tool."""

from database.connection import get_db, init_db, close_db
from database.models import (
    Expert,
    Conversation,
    Turn,
    SpanAnnotation,
    Relation,
    SpikesAnnotation,
)
from database.crud import (
    # Experts
    create_expert,
    get_expert,
    get_expert_by_name,
    get_all_experts,
    get_or_create_expert,
    # Conversations
    create_conversation,
    get_conversation,
    get_conversation_by_external_id,
    get_all_conversations,
    # Turns
    create_turn,
    get_turn,
    get_turn_by_number,
    get_turns_by_conversation,
    # Annotations
    create_span_annotation,
    get_span_annotations,
    get_span_annotation_by_span_id,
    delete_span_annotation,
    create_relation,
    get_relations,
    delete_relation,
    set_spikes_annotation,
    get_spikes_annotation,
    # Bulk operations
    get_full_conversation_with_annotations,
    save_session_annotations,
    import_conversation_from_json,
)

__all__ = [
    "get_db",
    "init_db",
    "close_db",
    "Expert",
    "Conversation",
    "Turn",
    "SpanAnnotation",
    "Relation",
    "SpikesAnnotation",
    "create_expert",
    "get_expert",
    "get_expert_by_name",
    "get_all_experts",
    "get_or_create_expert",
    "create_conversation",
    "get_conversation",
    "get_conversation_by_external_id",
    "get_all_conversations",
    "create_turn",
    "get_turn",
    "get_turn_by_number",
    "get_turns_by_conversation",
    "create_span_annotation",
    "get_span_annotations",
    "get_span_annotation_by_span_id",
    "delete_span_annotation",
    "create_relation",
    "get_relations",
    "delete_relation",
    "set_spikes_annotation",
    "get_spikes_annotation",
    "get_full_conversation_with_annotations",
    "save_session_annotations",
    "import_conversation_from_json",
]
